from __future__ import annotations

from cookieleveling.infra.db.repos.user_flags_repo import (
    clear_user_deleted,
    clear_user_left,
    ensure_user,
    fetch_user,
    fetch_user_flags,
    mark_user_deleted,
    mark_user_left,
    set_excluded,
    set_optout,
    set_rank_visible,
    sync_excluded_users,
    upsert_user_profile,
    upsert_user_profiles,
)
from cookieleveling.infra.db.repos.voice_ranking_repo import (
    fetch_lifetime_candidates,
    fetch_rank_candidates,
    fetch_weekly_candidates,
)
from cookieleveling.infra.db.repos.voice_state_repo import (
    apply_voice_snapshot,
    fetch_voice_states,
    reset_voice_states,
    set_voice_state,
    upsert_voice_state,
)
from cookieleveling.infra.db.repos.voice_xp_repo import (
    add_user_weekly_xp,
    fetch_active_voice_users,
    fetch_lifetime_users,
    grant_xp,
    reset_season_xp,
    reset_weekly_xp,
    set_xp,
    update_user_xp,
)

__all__ = [
    "add_user_weekly_xp",
    "apply_voice_snapshot",
    "clear_user_deleted",
    "clear_user_left",
    "ensure_user",
    "fetch_active_voice_users",
    "fetch_lifetime_candidates",
    "fetch_lifetime_users",
    "fetch_rank_candidates",
    "fetch_user",
    "fetch_user_flags",
    "fetch_voice_states",
    "fetch_weekly_candidates",
    "grant_xp",
    "mark_user_deleted",
    "mark_user_left",
    "reset_season_xp",
    "reset_voice_states",
    "reset_weekly_xp",
    "set_excluded",
    "set_optout",
    "set_rank_visible",
    "set_voice_state",
    "set_xp",
    "sync_excluded_users",
    "update_user_xp",
    "upsert_user_profile",
    "upsert_user_profiles",
    "upsert_voice_state",
]
